config/routes.rb
Rails.application.routes.draw do

  get 'authors/index'

  get 'authors/show'

  get 'pages/home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  resource :settings

  resources :sites
  resources :authors
  resources :texts
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  root 'pages#home'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :texts

  def self.find_or_create_best(options)
    twitter_handle = options["twitter"]
    author_name = options["name"]
    return nil if twitter_handle.nil? and author_name.nil?
    unless twitter_handle.nil?
      author = find_by(twitter: twitter_handle)
    end
    if author.nil?
      author = find_by(name: author_name)
    end
    if author.nil?
      author = create(
        twitter: twitter_handle,
        name: author_name,
      )
    end
    author
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @texts = @author.texts
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<% @authors.each do |author| %>
  <%= link_to author.name, author_path(author) %><br>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<h2><%= @author.twitter %></h1>
<ul>
  <% @texts.each do |text| %>
    <li>
      <%= link_to text.title, text_path(text) %>
      Versions: <%= text.version_count %>
    </li>
  <% end %>
</ul>